# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(416, 188)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_naklad = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_naklad.setGeometry(QtCore.QRect(270, 140, 141, 23))
        self.pushButton_naklad.setObjectName("pushButton_naklad")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(10, 20, 351, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton_file = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_file.setGeometry(QtCore.QRect(10, 50, 171, 23))
        self.pushButton_file.setObjectName("pushButton_file")
        self.pushButton_sklad = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_sklad.setGeometry(QtCore.QRect(10, 110, 171, 23))
        self.pushButton_sklad.setObjectName("pushButton_sklad")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(10, 80, 351, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ОЗОН-Склад"))
        self.pushButton_naklad.setText(_translate("MainWindow", "Создать накладную"))
        self.pushButton_file.setText(_translate("MainWindow", "Выбери файл с ОЗОНА"))
        self.pushButton_sklad.setText(_translate("MainWindow", "Выбрать путь к складу"))
